# Generated by Django 3.2.7 on 2021-10-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_auto_20211016_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-name']},
        ),
    ]
